#!/usr/bin/env bash
# setup.sh
# ─────────────────────────────────────────────────────────────────────────────
# VERITAS first-time setup.
# Run once after downloading. Safe to re-run at any time to check health.
#
# This script creates a Python virtual environment inside the veritas/
# folder and installs all dependencies into it. Nothing is installed
# into the system Python. This avoids the PEP 668 "externally managed
# environment" error on Ubuntu 24.04 and later.
#
# After setup, all commands use the venv automatically via the
# python and python3 wrapper scripts written into this folder.
#
# Usage:
#   cd veritas_v5/
#   bash setup.sh
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail
VERITAS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$VERITAS_DIR"

echo ""
echo "══════════════════════════════════════════════════════════"
echo "  VERITAS setup"
echo "══════════════════════════════════════════════════════════"
echo ""

# ── 1. Find system Python ─────────────────────────────────────────────────────
echo "[ 1/6 ] Checking Python..."

SYS_PYTHON=""
for c in python3.12 python3.11 python3.10 python3; do
    if command -v "$c" &>/dev/null; then SYS_PYTHON="$c"; break; fi
done

if [ -z "$SYS_PYTHON" ]; then
    echo "  ERROR: Python 3.10 or higher is required but was not found."
    echo "  Install with: sudo apt install python3.12 python3.12-venv"
    exit 1
fi

PY_VERSION=$("$SYS_PYTHON" --version 2>&1 | awk '{print $2}')
echo "  Found: $SYS_PYTHON ($PY_VERSION)"

# ── 2. Create virtual environment ─────────────────────────────────────────────
echo ""
echo "[ 2/6 ] Setting up virtual environment..."

VENV_DIR="$VERITAS_DIR/.venv"

if [ ! -d "$VENV_DIR" ]; then
    # python3-venv must be installed for this to work
    if ! "$SYS_PYTHON" -m venv --help &>/dev/null; then
        echo "  ERROR: python3-venv is not installed."
        echo "  Install with: sudo apt install python3-venv"
        echo "  Or:           sudo apt install python3.12-venv"
        exit 1
    fi
    "$SYS_PYTHON" -m venv "$VENV_DIR"
    echo "  Created: $VENV_DIR"
else
    echo "  Already exists: $VENV_DIR"
fi

# The Python binary inside the venv — this is what we use for everything
VENV_PYTHON="$VENV_DIR/bin/python"
VENV_PIP="$VENV_DIR/bin/pip"

# ── 3. Install dependencies into the venv ─────────────────────────────────────
echo ""
echo "[ 3/6 ] Installing Python dependencies into venv..."

"$VENV_PIP" install --quiet --upgrade pip
"$VENV_PIP" install --quiet -r "$VERITAS_DIR/requirements.txt"
echo "  Done."

# ── 4. Write python wrapper scripts ──────────────────────────────────────────
# These let you type "python run_veritas.py" instead of
# ".venv/bin/python run_veritas.py" every time.
# They are written into the veritas/ folder and are listed in .gitignore.
echo ""
echo "[ 4/6 ] Writing convenience wrappers..."

cat > "$VERITAS_DIR/python" << WRAPPER
#!/usr/bin/env bash
# Auto-generated by setup.sh — uses the VERITAS virtual environment.
exec "$VENV_DIR/bin/python" "\$@"
WRAPPER
chmod +x "$VERITAS_DIR/python"

# Also write a python3 alias pointing at the same venv
cat > "$VERITAS_DIR/python3" << WRAPPER
#!/usr/bin/env bash
exec "$VENV_DIR/bin/python" "\$@"
WRAPPER
chmod +x "$VERITAS_DIR/python3"

echo "  Written: ./python  (uses .venv)"
echo "  Written: ./python3 (uses .venv)"
echo ""
echo "  You can now run commands as:"
echo "    python run_veritas.py --list-candidates"
echo "  instead of:"
echo "    .venv/bin/python run_veritas.py --list-candidates"

# ── 5. Check required system tools ────────────────────────────────────────────
echo ""
echo "[ 5/6 ] Checking required system tools..."

missing_tools=()

for tool in binwalk; do
    if ! command -v "$tool" &>/dev/null; then
        missing_tools+=("$tool")
    fi
done

if [ "${#missing_tools[@]}" -gt 0 ]; then
    echo "  Missing required system tool(s): ${missing_tools[*]}"
    echo ""
    echo "  Install them with:"
    echo "    sudo apt update"
    echo "    sudo apt install -y ${missing_tools[*]}"
    echo ""
    echo "  Then re-run:"
    echo "    bash setup.sh"
    exit 1
fi

echo "  Required system tools found."

# ── 6. Run the VERITAS self-check ─────────────────────────────────────────────
echo ""
echo "[ 6/6 ] Running self-check..."

"$VENV_PYTHON" veritas_selfcheck.py

# Make adapter scripts executable and create output dirs
find candidates/ -name "run_adapter.sh" -exec chmod +x {} \; 2>/dev/null || true
mkdir -p results/runs results/logs results/unpack_cache reports

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo "══════════════════════════════════════════════════════════"
echo "  Setup complete."
echo ""
echo "  All commands below use ./python which points at the venv."
echo "  You do not need to activate the venv manually."
echo ""
echo "  Register your tools:"
echo "    python run_veritas.py --register-tool ~/Desktop/FirmAE"
echo "    python run_veritas.py --register-tool ~/firmadyne"
echo "    python run_veritas.py --register-tool ~/emba"
echo ""
echo "  Confirm registration:"
echo "    python run_veritas.py --list-candidates"
echo ""
echo "  Test the service probe:"
echo "    python probes/probe_service.py --ip 127.0.0.1 --port 80"
echo ""
echo "  Dry run:"
echo "    python run_veritas.py --firmware /path/to/firmware_folder --dry-run"
echo ""
echo "  Full benchmark:"
echo "    python run_veritas.py --firmware /path/to/firmware_folder --candidates firmae,firmadyne,emba"
echo ""
echo "  Generate report:"
echo "    python score_aggregator.py"
echo ""
echo "══════════════════════════════════════════════════════════"
echo ""
