name = FirmAE
id = firmae
tool_source = git
tool_local_path = /home/ubuntu/Desktop/FirmAE
tool_repo = https://github.com/pr0v3rbs/FirmAE.git
success_signals = Network reachable on, Web service on
supported_architectures = arm, mips, mipsel, mips64, x86
requires_sudo = true
